### ISSUE TITLE
Moving the map should refresh the list of location results 

### ISSUE THREAD

**Issue by sumitsekhri** [findthemasks/findthemasks#632] opened 2020-04-20 17:37 UTC
When a user moves the map around the list of results on the lefthand side should reflect what is currently in view on the map.

**Comment by ngottlieb** [comment] 2020-04-20 17:39
duplicate of #627 (@sumitsekhri: @saikatbhadra had already split the issue for you, sorry!)

**Closed by ngottlieb** 2020-04-20 17:39 UTC
