### ISSUE TITLE
Generate filter-by items based on data instead of hard-coding them/Filter by Items do not match Google Form items - [US/CA/FR/all]

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#402] opened 2020-04-01 07:46 UTC
The items we allow hospitals to check off on the Google Form do not match the Filter items. See here for US-form vs. US-filter list example. It's the same issue on Canada and France form/pages:
![image](https://user-images.githubusercontent.com/62862914/78111379-6c346480-73b1-11ea-9f60-06ffb6cebd98.png)

This mismatch does not allow us to provide full usability to this dataset. 
For example, now that the maker community is growing to produce homemade masks and 3D printed items, they need a reliable way to filter by "homemade mask" for example, which will only display hospitals that have been allowed to receive such non-medical grade items.

Although times are dire, there are institutional regulations and policies when it comes to PPE. There is a tension between frontline medical staff and hospital administration who must think about resource management as well as risk management (read: lawsuits). If we offer hospitals etc the option to select "homemade masks" on our Google Forms, we need to also make sure to help our users best navigate our data by providing that as a corresponding Filter Item.

**Comment by drwestco** [comment] 2020-04-02 17:07
Is there a way the data can tell us the list of filters to show, instead of having it hard-coded in the site script? I'm imagining a new blob of data with key/value for each item type - key would be a canonical short code used to identify the type, value would be the display text for the filter control. Each location row would also have a field with a list of keys for the items accepted at that location.

**Comment by awong-dev** [comment] 2020-04-03 14:45
@drwestco this is a good idea. The "MergeConfig" tab has this info. We need to dump and parse.

**Comment by nburt** [comment] 2020-04-03 15:05
I'd also like to integrate this with translation as well. Since we're using the MergeConfig to write enums into English we'll need to translate them into the user's selected locale when displaying them in map popups + the locations list.

**Comment by cgrayson** [comment] 2020-04-07 12:58
Suggest renaming this issue to something like, "Generate filter-by items based on data instead of hard-coding it". (The filter-by items do match the form items, for now; see my screenshot on #401.)

**Comment by cgrayson** [comment] 2020-04-07 13:17
> The "MergeConfig" tab has this info. We need to dump and parse.

I'm confused about this. When I look at the "MergeConfig" tab of the spreadsheet, I don't see much data: 

<img width="305" alt="Screen Shot 2020-04-07 at 8 12 08 AM" src="https://user-images.githubusercontent.com/5596/78673742-2cd1b080-78a8-11ea-835b-2d9c1c0bf2a0.png">

**Comment by nburt** [comment] 2020-04-07 13:41
FYI this is in PR right now: https://github.com/findthemasks/findthemasks/pull/494

@cgrayson which merge config form is that? Merge Config is not implemented in the US yet

**Comment by cgrayson** [comment] 2020-04-07 14:41
Ah, ok, probably my misunderstanding the terminology. I saw a tab on the the main Google Sheet for donations titled "MergeConfig", but it must be something else (or not implemented, as you say).

**Comment by awong-dev** [comment] 2020-04-07 16:00
Actually... I silently launched merging on the US... It mostly works minus
the filter translation output. I can fix that.

**Comment by nburt** [comment] 2020-04-07 16:11
🙌 ok - I merged config based dynamic filters with some special casing for us... I'll follow up on this tonight

**Comment by linderr** [comment] 2020-04-07 18:53
@awong-dev I noticed that lol. Messaged in #dev to ask when to expect for rest of the world?

**Comment by awong-dev** [comment] 2020-04-07 19:11
@linderr someone else will have to coordinate. all the pieces are there... it's mostly about validating its working I think.

The trick is for the single-language sites, someone has to write out a list of all filter items in the canonical column.

Alternately, we could dynamically generate it by scraping through every element, but the manual process seems better for now...

**Comment by linderr** [comment] 2020-04-07 21:44
Does Vlad have the skills to put the puzzle together? He hasn't 2FA'd GH yet b/c of work but we can maybe ask him if he's capable

**Comment by awong-dev** [comment] 2020-04-07 22:18
@nburt understands it the best. But anyone who can read/write JS can sort it out. The question is really how fast...

**Comment by ngottlieb** [comment] 2020-04-12 00:25
@linderr you can test this here: https://findthemasks-feature-dy-9pnbes.herokuapp.com/

by my own testing it works across all countries and languages...but it's possible I missed something so other testing would be appreciated.

Basically, we look at the data for a given country, parse out all the possible accepted items, and then only display filters for ones that match the defined filters in `filterEnumLookup.js` -- meaning, if we want to add new possibilities they need to be added there, but they don't need to be added country specific.

**Comment by linderr** [comment] 2020-04-12 02:16
@ngottlieb thanks so much for working on this! Going to try to play/break now :)

**Comment by linderr** [comment] 2020-04-12 02:21
You may have it set up all correctly on the backend but the output is still this. Can you add the new Form items to your "defined filters in filterEnumLookup.js" ? 
![image](https://user-images.githubusercontent.com/62862914/79058998-91cf3280-7c29-11ea-95d3-c8a0a4b2b895.png)

**Comment by linderr** [comment] 2020-04-12 02:25
@ngottlieb the CA website doesn't even show N95 masks for example lol......
![image](https://user-images.githubusercontent.com/62862914/79059033-1fab1d80-7c2a-11ea-8e49-c6bf7512026a.png)

**Comment by ngottlieb** [comment] 2020-04-12 02:29
@linderr  are you looking at the example site or at production? This hasn't been merged. Production doesn't show N95s for Canada, my new branch does.

https://findthemasks-feature-dy-9pnbes.herokuapp.com/ca/

**Comment by ngottlieb** [comment] 2020-04-12 02:30
My new one also shows the US filters you reference as being missing.

**Comment by linderr** [comment] 2020-04-12 02:32
@ngottlieb I used the first link you shared (US) and used the country selector at the bottom to nav to other countries. I see on your /ca/ "n95s" are now listed. But both sites are missing "Homemade" and "Face Shields - 3D printed/makerspace" ---- these are new canonical items approved last week

**Comment by linderr** [comment] 2020-04-12 02:32
![image](https://user-images.githubusercontent.com/62862914/79059108-34d47c00-7c2b-11ea-999a-3a4ed2e1e78d.png)

**Comment by linderr** [comment] 2020-04-12 02:34
Although I have NO idea what the logic behind any of this is --- it sounds like for "homemade masks" and "Face shields - 3D printed/makerspace" just needs to be added as defined filters in filterEnumLookup.js ???

**Comment by ngottlieb** [comment] 2020-04-12 02:59
got it, sorry, yes -- I'll add them to filterEnumLookup.js.

Also, to clarify, if they don't actually have any of the item in question, it doesn't show up whether or not that filter would be "valid" -- so for France, there *are* no 3d printed things listed in "Accepting" anywhere, as far as I can tell. That's (at least one reason) why they don't show up.

**Comment by linderr** [comment] 2020-04-12 03:35
Interesting. Yes, that makes sense. 

I just checked our dataset for "Face shields - 3D printed/makerspace" --- there should be 27 hits in Canada. Filter does not show up?

**Comment by linderr** [comment] 2020-04-12 03:39
@ngottlieb likewise for France, their form also includes the French versions of "homemade masks" and "3D printed/makerspace" for face shields. 

I understand the logic that no selection yields no filter button (similarly the provincial tiles only show up when there is a first pin in that province). Let me know when you update filterEnumLookup.js so we can test the Canadian filter since we know it should give us ~27 results :)

**Comment by ngottlieb** [comment] 2020-04-12 03:39
Yeah I mean -- we have 'faceshields - 3d-printed or makerspace (specify type in other)' whitelisted. https://github.com/findthemasks/findthemasks/blob/9804d400a26c85c9d46f769096b0b5a7ec4d5580/public/formEnumLookups.js#L14-L16

More than anything else it seems like a miscommunication that they would be subtly different between countries (one has `specify type in other` and the other doesn't). I can add it, but that doesn't seem like the right answer.

And, regarding France, again, like I said above -- there is nothing in the French data that includes the word "3D," so even if it's whitelisted (which it is), those filters won't show up and that seems like the desired behavior to me.

**Comment by linderr** [comment] 2020-04-12 03:41
if row 14 is character specific, we will not satisfy the "(specify type in other)" portion --- also this does not make sense in the context. There are hundreds of makerspace models now available. The hospital will not know that information, as it's essentially DIY.

**Comment by ngottlieb** [comment] 2020-04-12 03:42
they're all character specific, we're matching a whitelist. Why does the US one says "Specify type in other?" Do we need that? It just seems weird to have that difference between two otherwise identical fields in two countries. I can add the additional version, but it seems like the more sensible process for this particular one would be to match the two in the Google form.

**Comment by linderr** [comment] 2020-04-12 03:45
I agree with you --- Also, doing a quick Ctrl+f on the US data, there should be over 230 locations requesting "face shields - 3D printed/makerspace" yet the tile is not triggered on your herokuapp link

**Comment by ngottlieb** [comment] 2020-04-12 03:53
Yeah, I see the cause of that one -- there's a typo. You can see on production that field doesn't get translated, same issue, I will fix.

**Comment by linderr** [comment] 2020-04-12 04:03
Looking through, none of the 50ish i've checked so far in the US data actually indicated any additional information regarding type when checking off "3D printed/maker space".

The context here is not like standard, medical grade PPE where they can just be like "3M 1860" to specify a item's model number. Homemade and makerspace items are a smorgasbord/free for all. It's a "whatever fits" model. 

I think just adding an additional permutation of "homemade masks" and "face shields - 3D printed/maker space" without the (specify type) part is a fair work around. Otherwise, we'll have to back-edit all the hits to match the character-sensitivity. Less man hours to just add another "item" on the whitelist :)

**Comment by ngottlieb** [comment] 2020-04-12 15:39
Well -- sigh -- I added the following "new" fields to our canonical list:

- `handmade masks` (because in France, it's handmade instead of homemade)
- `homemade masks` (minus the "specify type" clause
- `face shields - 3d-printed or makerspace` (minus the "specify type" clause)

I believe that fixes all the issues you were raising (though the translations won't work until smartling finishes translating the "new" fields). Again, I'm looking at the France data and there are *no* entries that include anything with the phrase "3d" so that's why no filters are showing up about 3d printed things.

This also fixes bugs on production where each of those accepted items were not being translated.

**Closed** 2020-04-12 18:04 UTC
Labels: bug, high-priority
