### ISSUE TITLE
Add Google-Maps directions link to the address in map-bubble/listings

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#389] opened 2020-03-31 23:14 UTC
Seems like an easy addition that might help conversion to connect donors with recipients.

Downside: May encourage people to go direct to the address without contacting recipient ahead of time.

**Comment by saikatbhadra** [comment] 2020-04-02 05:30
Duplicate of https://github.com/findthemasks/findthemasks/issues/126

**Closed by saikatbhadra** 2020-04-02 05:30 UTC
Labels: duplicate, enhancement
